# Generated by Django 5.2.10 on 2026-01-11 13:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nota_fiscal', models.CharField(max_length=48)),
                ('data_nf', models.DateTimeField()),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_insumo', models.CharField(max_length=64)),
                ('qtd_disponivel', models.IntegerField()),
                ('und_medida', models.CharField(max_length=8)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='insumos/')),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=64)),
                ('qtd_disponivel', models.IntegerField()),
                ('peso_cont', models.IntegerField()),
                ('und_medida', models.CharField(max_length=20)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id_item_compra', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_item_compra', models.IntegerField()),
                ('peso_cont', models.IntegerField()),
                ('und_medida', models.CharField(max_length=8)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.compra')),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
            ],
            options={
                'db_table': 'item_compra',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome_receita', models.CharField(max_length=64)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'db_table': 'receita',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id_producao', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_produzida', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('receita', models.ForeignKey(db_column='id_receita', on_delete=django.db.models.deletion.CASCADE, to='core.receita')),
            ],
            options={
                'db_table': 'producao',
            },
        ),
        migrations.CreateModel(
            name='ItemReceita',
            fields=[
                ('id_item_receita', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('medida_caseira', models.CharField(max_length=64)),
                ('peso_cont', models.IntegerField()),
                ('und_medida', models.CharField(max_length=8)),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
                ('receita', models.ForeignKey(db_column='id_receita', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receita')),
            ],
            options={
                'db_table': 'item_receita',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id_item_venda', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('venda', models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.venda')),
            ],
            options={
                'db_table': 'item_venda',
            },
        ),
    ]
