# Generated by Django 5.2.10 on 2026-01-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='qtd_da_receita',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
