# Generated by Django 6.0.3 on 2026-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producao_qtd_da_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(default='Dinheiro', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='data_nf',
            field=models.DateField(),
        ),
    ]
