# Generated by Django 6.0.3 on 2026-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemcompra_data_validade_venda_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix')], default='DINHEIRO', max_length=10),
        ),
    ]
