# Generated by Django 6.0.4 on 2026-05-16 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=128)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'despesa',
            },
        ),
    ]
